version: '3.8'

services:
  db-farmacia:
    image: mysql:8.0
    container_name: db-farmacia
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      TZ: "America/Bahia"
    command: >
      --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - db-farmacia:/var/lib/mysql
    networks:
      - app-network

volumes:
  db-farmacia:

networks:
  app-network:
    driver: bridge
