version: '3.8'

services:
  farmacia-db:
    build:
      context: .
      dockerfile: Dockerfile-db
    image: farmacia-db-imagem
    container_name: farmacia-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      TZ: "America/Bahia"
    command: >
      --default-authentication-plugin=mysql_native_password
    volumes:
      - farmacia-db-volume:/var/lib/mysql
    networks:
      - app-network

  farmacia-api-gerenciamento:
    build:
      context: .
      dockerfile: Dockerfile-api-gerenciamento
    image: farmacia-api-gerenciamento-imagem
    container_name: farmacia-api-gerenciamento
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT: ${MYSQL_ROOT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PORT: ${MYSQL_PORT}
    networks:
      - app-network
    depends_on:
      - farmacia-db
  
  farmacia-api-relatorio:
    build:
      context: .
      dockerfile: Dockerfile-api-relatorio
    image: farmacia-api-relatorio-imagem
    container_name: farmacia-api-relatorio
    ports:
      - "3030:3000"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PORT: ${MYSQL_PORT}
    networks:
      - app-network
    depends_on:
      - farmacia-db

volumes:
  farmacia-db-volume:

networks:
  app-network:
    driver: bridge
