CREATE TABLE IF NOT EXISTS clientes (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(100) NOT NULL,
	cpf VARCHAR(100) UNIQUE NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS vendedores (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(100) NOT NULL,
	cpf VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS itens (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(100) NOT NULL,
	preco DOUBLE(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS estoque (
	id INT AUTO_INCREMENT PRIMARY KEY,
	id_item INT UNIQUE NOT NULL,
	quantidade_atual INT NOT NULL,
	FOREIGN KEY(id_item) REFERENCES itens(id)
);

CREATE TABLE IF NOT EXISTS vendas (
	id INT AUTO_INCREMENT PRIMARY KEY,
	id_cliente INT NOT NULL,
	id_vendedor INT NOT NULL,
	data_hora DATETIME NOT NULL,
	status VARCHAR(100) NOT NULL,
	total DOUBLE(10, 2) NOT NULL,
	FOREIGN KEY(id_cliente) REFERENCES clientes(id),
	FOREIGN KEY(id_vendedor) REFERENCES vendedores(id)
);

CREATE TABLE IF NOT EXISTS vendas_detalhes (
	id INT AUTO_INCREMENT PRIMARY KEY,
	id_venda INT NOT NULL,
	id_item INT NOT NULL,
	quantidade INT NOT NULL,
	preco INT NOT NULL,
	FOREIGN KEY(id_venda) REFERENCES vendas(id),
	FOREIGN KEY(id_item) REFERENCES itens(id)
);